"""Type stubs for the media_processor Rust extension (PyO3)."""

class ImageData:
    # NOTE: ``data`` is a constructor arg but NOT a readable attribute (the
    # Rust field has no #[pyo3(get)]); use get_data(). Only these four are
    # readable as attributes.
    width: int
    height: int
    channels: int
    format: str

    def __init__(
        self, data: bytes, width: int, height: int, channels: int, format: str
    ) -> None: ...
    def get_data(self) -> bytes: ...
    def to_base64(self) -> str: ...
    def __len__(self) -> int: ...

class MediaProcessor:
    def __init__(self, max_dimension: int = 1024, jpeg_quality: int = 85) -> None: ...
    def load(self, data: bytes) -> ImageData: ...
    def resize(
        self, data: bytes, max_width: int | None = None, max_height: int | None = None
    ) -> ImageData: ...
    def resize_exact(self, data: bytes, width: int, height: int) -> ImageData: ...
    def thumbnail(self, data: bytes, size: int) -> ImageData: ...
    @staticmethod
    def is_animated(data: bytes) -> bool: ...
    @staticmethod
    def get_dimensions(data: bytes) -> tuple[int, int]: ...
    @staticmethod
    def encode_base64(data: bytes) -> str: ...
    @staticmethod
    def decode_base64(encoded: str) -> bytes: ...
    def batch_resize(
        self, images: list[bytes], max_width: int, max_height: int
    ) -> list[ImageData]: ...
    @staticmethod
    def detect_format(data: bytes) -> str | None: ...

def py_is_animated(data: bytes) -> bool: ...
def py_get_dimensions(data: bytes) -> tuple[int, int]: ...
def py_to_base64(data: bytes) -> str: ...

# Module-level attributes added by the #[pymodule] fn (src/lib.rs:312-313).
__version__: str
__author__: str
