"""Type stubs for the rag_engine Rust extension (PyO3)."""

__version__: str
__author__: str

class MemoryEntry:
    id: str
    text: str
    timestamp: float
    importance: float

    def __init__(
        self, id: str, text: str, embedding: list[float], timestamp: float, importance: float
    ) -> None: ...
    def get_embedding(self) -> list[float]: ...

class SearchResult:
    id: str
    text: str
    score: float
    timestamp: float

class RagEngine:
    def __init__(self, dimension: int = 384, similarity_threshold: float = 0.7) -> None: ...
    def add(self, entry: MemoryEntry) -> None: ...
    def add_batch(self, entries_list: list[MemoryEntry]) -> int: ...
    def remove(self, id: str) -> bool: ...
    def search(
        self,
        query_embedding: list[float],
        top_k: int = 5,
        time_decay_factor: float = 0.0,
    ) -> list[SearchResult]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...
    def get_ids(self) -> list[str]: ...
    def get(self, id: str) -> MemoryEntry | None: ...
    @staticmethod
    def compute_similarity(a: list[float], b: list[float]) -> float: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> int: ...
