-- Migration 011: (retired) previously rebuilt ai_analytics to fix its model
-- default while preserving historical per-row values.
--
-- The ai_analytics table and its analytics subsystem were removed (the
-- subsystem was dead-wired and never recorded anything in production). On a
-- FRESH database ai_analytics is no longer created by schema init, so this
-- migration's old CREATE / INSERT-SELECT FROM ai_analytics / RENAME body would
-- fail with "no such table". It is now a no-op; migration 017 drops the table
-- on any EXISTING database that still has it. Kept as a numbered no-op so the
-- version sequence and already-applied schema_version rows stay intact.
SELECT 1;
